services:
  app:
    build: .
    image: miorg/mimicro:dev
    container_name: mimicro
    ports:
      - "8080:8080"
      - "5005:5005"   # Debug remoto
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Dspring.profiles.active=docker
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=appdb
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: